#!/bin/bash

# ==========================================================
# NAS-TUI v2.1
# Alpine Linux + Samba + OpenRC + Proxmox LXC
# Rutas absolutas para máxima compatibilidad
# ==========================================================


# ----------------------------------------------------------
# BINARIOS
# ----------------------------------------------------------

DIALOG="/usr/bin/dialog"

TESTPARM="/usr/bin/testparm"
SMBPASSWD="/usr/bin/smbpasswd"
PDBEDIT="/usr/bin/pdbedit"
SMBSTATUS="/usr/bin/smbstatus"

RCSERVICE="/sbin/rc-service"
RCUPDATE="/sbin/rc-update"

LS="/bin/ls"
CP="/bin/cp"
MKDIR="/bin/mkdir"
RM="/bin/rm"
CAT="/bin/cat"
MV="/bin/mv"
DATE="/bin/date"
DF="/bin/df"

BTOP="/usr/bin/btop"
NANO="/usr/bin/nano"


# ----------------------------------------------------------
# VARIABLES
# ----------------------------------------------------------

export TERM=xterm


SMB_DIR="/etc/samba"

SHARE_DIR="$SMB_DIR/smb.conf.d"

DYNAMIC_CONF="$SMB_DIR/smb_dynamic.conf"

BACKUP_DIR="/root/samba_backups"

DEFAULT_GROUP="nasusers"


TMP_DIR="/tmp/nas-tui"

$MKDIR -p "$TMP_DIR"
$MKDIR -p "$SHARE_DIR"
$MKDIR -p "$BACKUP_DIR"



# ----------------------------------------------------------
# CHEQUEO INICIAL
# ----------------------------------------------------------

check_bin()
{
    if [ ! -x "$1" ]
    then
        echo "Falta comando: $1"
        exit 1
    fi
}


for BIN in \
"$DIALOG" \
"$TESTPARM" \
"$SMBPASSWD" \
"$PDBEDIT" \
"$SMBSTATUS" \
"$RCSERVICE" \
"$RCUPDATE"
do
    check_bin "$BIN"
done



# ----------------------------------------------------------
# FUNCIONES BASE
# ----------------------------------------------------------

msg()
{
    "$DIALOG" \
    --title "NAS-TUI" \
    --msgbox "$1" 10 60
}



confirm()
{
    "$DIALOG" \
    --title "Confirmar" \
    --yesno "$1" 10 60
}



input()
{
    "$DIALOG" \
    --stdout \
    --inputbox "$1" 10 60
}



# ----------------------------------------------------------
# SAMBA CONFIG
# ----------------------------------------------------------

backup_config()
{

    if [ -f "$DYNAMIC_CONF" ]
    then

        "$CP" "$DYNAMIC_CONF" \
        "$BACKUP_DIR/smb-$( $DATE +%Y%m%d-%H%M%S ).conf"

    fi

}



sync_config()
{

    backup_config


    : > "$DYNAMIC_CONF"


    for FILE in "$SHARE_DIR"/*.conf
    do

        [ -f "$FILE" ] || continue


        "$CAT" "$FILE" >> "$DYNAMIC_CONF"


        echo "" >> "$DYNAMIC_CONF"

    done

}



validate_samba()
{

    "$TESTPARM" -s >/dev/null 2>&1

}



restart_samba()
{

    if validate_samba
    then

        "$RCSERVICE" samba restart


        msg "Samba reiniciado correctamente"

    else

        msg "ERROR

La configuración Samba no es válida"

    fi

}



# ----------------------------------------------------------
# ESTADO GENERAL
# ----------------------------------------------------------

show_file()
{

    "$DIALOG" \
    --title "$1" \
    --textbox "$2" 35 100

}

# ==========================================================
# USUARIOS SAMBA
# ==========================================================


ensure_group()
{

    getent group "$DEFAULT_GROUP" >/dev/null 2>&1

    if [ $? -ne 0 ]
    then
        addgroup "$DEFAULT_GROUP"
    fi

}



create_user()
{

    ensure_group


    USER=$(input "Nombre del usuario")


    [ -z "$USER" ] && return



    if id "$USER" >/dev/null 2>&1
    then

        msg "El usuario ya existe"

        return

    fi



    adduser -D -H -s /sbin/nologin "$USER"

    passwd -l "$USER"


    addgroup "$USER" "$DEFAULT_GROUP"



    "$SMBPASSWD" -a "$USER"



    msg "Usuario creado:

$USER"

}



delete_user()
{

    USER=$(input "Usuario a eliminar")


    [ -z "$USER" ] && return



    if confirm "Eliminar usuario:

$USER ?"
    then

        "$SMBPASSWD" -x "$USER" 2>/dev/null


        deluser "$USER"


        msg "Usuario eliminado"

    fi

}



change_password()
{

    USER=$(input "Usuario Samba")


    [ -z "$USER" ] && return



    "$SMBPASSWD" "$USER"



    msg "Contraseña actualizada"

}



list_users()
{

    "$PDBEDIT" -L > "$TMP_DIR/users.txt" 2>&1


    show_file \
    "Usuarios Samba" \
    "$TMP_DIR/users.txt"

}



users_menu()
{

while true
do


OPTION=$(
"$DIALOG" \
--stdout \
--title "Usuarios Samba" \
--menu "Gestión usuarios" \
16 70 10 \
1 "Crear usuario" \
2 "Eliminar usuario" \
3 "Cambiar contraseña" \
4 "Lista usuarios" \
0 "Volver"
)



case "$OPTION" in

1)
create_user
;;

2)
delete_user
;;

3)
change_password
;;

4)
list_users
;;

0)
break
;;

esac


done

}

# ==========================================================
# SHARES SAMBA
# ==========================================================


list_share_files()
{

    SHARE_LIST=()


    for FILE in "$SHARE_DIR"/*.conf
    do

        [ -f "$FILE" ] || continue


        SHARE_LIST+=("$(basename "$FILE")")

    done

}



create_share()
{

    NAME=$(input "Nombre del share")


    [ -z "$NAME" ] && return



    PATH_SHARE=$(input "Ruta absoluta del share")


    [ -z "$PATH_SHARE" ] && return



    if [ ! -d "$PATH_SHARE" ]
    then

        if confirm "La ruta no existe.

Crear:

$PATH_SHARE ?"
        then

            "$MKDIR" -p "$PATH_SHARE"

        else

            return

        fi

    fi



    cat > "$SHARE_DIR/$NAME.conf" <<EOF
[$NAME]
   path = $PATH_SHARE
   browseable = yes
   writable = yes
   guest ok = no
   valid users = @$DEFAULT_GROUP
   force group = $DEFAULT_GROUP
   create mask = 0664
   directory mask = 0775

   # ==========================================
   # Control de acceso (Descomentar para usar)
   # ==========================================
   # valid users = usuario1, usuario2
   # invalid users = usuario_bloqueado
EOF



    sync_config


    restart_samba



    msg "Share creado:

$NAME"

}



list_shares()
{

    "$LS" -1 "$SHARE_DIR" \
    > "$TMP_DIR/shares.txt" 2>&1



    show_file \
    "Shares configurados" \
    "$TMP_DIR/shares.txt"

}



edit_share()
{

    list_share_files


    if [ ${#SHARE_LIST[@]} -eq 0 ]
    then

        msg "No hay shares"

        return

    fi



    MENU_ITEMS=()


    for FILE in "${SHARE_LIST[@]}"
    do

        MENU_ITEMS+=("$FILE" "editar")

    done



    FILE=$(
    "$DIALOG" \
    --stdout \
    --title "Editar Share" \
    --menu "Seleccione" \
    20 70 10 \
    "${MENU_ITEMS[@]}"
    )



    [ -z "$FILE" ] && return



    "$NANO" "$SHARE_DIR/$FILE"


    sync_config


    restart_samba

}



delete_share()
{

    list_share_files


    if [ ${#SHARE_LIST[@]} -eq 0 ]
    then

        msg "No hay shares"

        return

    fi



    MENU_ITEMS=()


    for FILE in "${SHARE_LIST[@]}"
    do

        MENU_ITEMS+=("$FILE" "borrar")

    done



    FILE=$(
    "$DIALOG" \
    --stdout \
    --title "Eliminar Share" \
    --menu "Seleccione" \
    20 70 10 \
    "${MENU_ITEMS[@]}"
    )



    [ -z "$FILE" ] && return



    if confirm "Eliminar:

$FILE ?"
    then

        "$RM" -f "$SHARE_DIR/$FILE"


        sync_config


        restart_samba


        msg "Share eliminado"

    fi

}



shares_menu()
{

while true
do


OPTION=$(
"$DIALOG" \
--stdout \
--title "Shares Samba" \
--menu "Gestión de shares" \
16 70 10 \
1 "Crear share" \
2 "Editar share" \
3 "Eliminar share" \
4 "Lista shares" \
0 "Volver"
)



case "$OPTION" in

1)
create_share
;;

2)
edit_share
;;

3)
delete_share
;;

4)
list_shares
;;

0)
break
;;

esac


done

}

# ==========================================================
# SERVICIO SAMBA OPENRC
# ==========================================================


samba_status()
{

    {
        echo "=============================="
        echo " ESTADO SAMBA"
        echo "=============================="

        "$RCSERVICE" samba status


        echo
        echo "=============================="
        echo " INICIO AUTOMATICO"
        echo "=============================="



        "$RCUPDATE" show default | grep -q samba

        if [ $? -eq 0 ]
        then
            echo "HABILITADO"
        else
            echo "DESHABILITADO"
        fi


        echo
        echo "=============================="
        echo " CLIENTES"
        echo "=============================="


        "$SMBSTATUS"

    } > "$TMP_DIR/samba-status.txt" 2>&1



    show_file \
    "Estado Samba" \
    "$TMP_DIR/samba-status.txt"

}



samba_start()
{

    "$RCSERVICE" samba start


    msg "Samba iniciado"

}



samba_stop()
{

    "$RCSERVICE" samba stop


    msg "Samba detenido"

}



samba_restart()
{

    restart_samba

}



samba_enable()
{

    "$RCUPDATE" add samba default


    msg "Samba habilitado al inicio"

}



samba_disable()
{

    "$RCUPDATE" del samba default


    msg "Samba deshabilitado del inicio"

}



samba_menu()
{

while true
do


OPTION=$(
"$DIALOG" \
--stdout \
--title "Servicio Samba" \
--menu "OpenRC" \
18 70 12 \
1 "Estado Samba" \
2 "Iniciar Samba" \
3 "Detener Samba" \
4 "Reiniciar Samba" \
5 "Habilitar inicio automático" \
6 "Deshabilitar inicio automático" \
0 "Volver"
)



case "$OPTION" in

1)
samba_status
;;

2)
samba_start
;;

3)
samba_stop
;;

4)
samba_restart
;;

5)
samba_enable
;;

6)
samba_disable
;;

0)
break
;;

esac


done

}




# ==========================================================
# SISTEMA
# ==========================================================


system_menu()
{

while true
do


OPTION=$(
"$DIALOG" \
--stdout \
--title "Sistema" \
--menu "Herramientas" \
15 70 10 \
1 "Monitor btop" \
2 "Diagnóstico almacenamiento" \
0 "Volver"
)



case "$OPTION" in


1)

"$BTOP"

;;


2)

{

echo "=============================="
echo " ESPACIO"
echo "=============================="

"$DF" -h


echo
echo "=============================="
echo " MONTAJES"
echo "=============================="

mount


echo
echo "=============================="
echo " /srv/data"
echo "=============================="

ls -ldn /srv/data 2>&1


echo
echo "=============================="
echo " IDENTIDAD"
echo "=============================="

id


echo
echo "=============================="
echo " GRUPOS"
echo "=============================="

groups


} > "$TMP_DIR/storage.txt" 2>&1



show_file \
"Diagnóstico almacenamiento" \
"$TMP_DIR/storage.txt"

;;

0)
break
;;

esac


done

}



# ==========================================================
# BACKUPS
# ==========================================================


manual_backup()
{

    if [ -f "$DYNAMIC_CONF" ]
    then

        "$CP" "$DYNAMIC_CONF" \
        "$BACKUP_DIR/manual-$("$DATE" +%Y%m%d-%H%M%S).conf"


        msg "Backup creado:

$BACKUP_DIR"

    else

        msg "No existe:

$DYNAMIC_CONF"

    fi

}



list_backups()
{

    "$LS" -lh "$BACKUP_DIR" \
    > "$TMP_DIR/backups.txt" 2>&1


    show_file \
    "Backups Samba" \
    "$TMP_DIR/backups.txt"

}



backup_menu()
{

while true
do


OPTION=$(
"$DIALOG" \
--stdout \
--title "Backups" \
--menu "Configuración Samba" \
15 70 10 \
1 "Crear backup" \
2 "Ver backups" \
0 "Volver"
)



case "$OPTION" in

1)
manual_backup
;;

2)
list_backups
;;

0)
break
;;

esac


done

}

# ==========================================================
# MENU PRINCIPAL
# ==========================================================


main_menu()
{

while true
do


OPTION=$(
"$DIALOG" \
--stdout \
--clear \
--title "NAS-TUI v2.1" \
--menu "Administrador NAS" \
20 75 12 \
1 "Usuarios Samba" \
2 "Shares Samba" \
3 "Servicio Samba" \
4 "Sistema" \
5 "Backups" \
0 "Salir"
)



case "$OPTION" in


1)

users_menu

;;


2)

shares_menu

;;


3)

samba_menu

;;


4)

system_menu

;;


5)

backup_menu

;;


0)

clear

exit 0

;;


esac


done

}



# ==========================================================
# INICIO
# ==========================================================


main_menu
